language: node_js
node_js:
  - 8.7

env:
  secure: "H58yEc5CU8d+mD/dmkU5kVA1u7mtC8mMWSEWlAo22DW34wHJazJg+jNDJeStk53EM58/l1HdT3nEnMEkw4x3j8qtT/wSCQZDe7/8NeGua9zGbJPuALjiD812v+uiQ7ULOqcO2kN+uMsUCJZoAgbmmeEJL2CfdPigwa9rT+l6C2qhlQK08+76edOyFNdQD88sGaHadWqFQvtf4oddEWOTypeJny2o2i4THXLLPGTYAMWaiHVRz59DYZ8z2x3YwqnxR01V074D3gu3aGo9zlhqj10nXxANI7AAUuT3VOb2ukokstPsJ5URGcpyka3OVXWcVmLNCccorLa0yP2nTJAa+JPwIuXmXYY5WRRm7obkVesT2AwvAv16bm5S0KsWYztnC6sD/lCrAC89haN44bxb4GV3uItCuqSjpj5veCmKhOHMkvvKJMPWgUw1YovzcaZ9HTh/TUtdCLlGTftYifWybEgpk6qg2UKT+Kpx1kezjH7HSRPoQ5DfSjUSYHvvqKwt2aK5VqSjWpxpivW6L3cTTruXNgXiGSLfFM7QuJ8aIDPvRjyWYKYZOdSkspzQw/LgLuH2YGTFBnMAt5/odU61nKEn7yk2EUyM6A7qV9FRt/S+ix4kKB+uaKtvJY4HRBNICfiI+8YpujDyeVLwwjWQiBLQ6abLNqqmaQuf2WzxX/8="
  secure: "fVrSeh+YFlrxJb6P70v+V9R9Y2Thk/nEcpoz9frOi5P7Jj6uztdpqnr+ZW+BvfjDEkjOpsmK5+efdQzWSw3P4ahmdfrO54aJ2reVlpntUaImbhRRjkNPD93RwXq1KJdD5tV0vbnGn3wyoNAWl3VlxRZnljRW4TjQnp7okE8b9+mXSZAsgDdXZ4d1Ljer9GbT7HzMOYGDUd8EZAHa1ZW6QohNEWVOHjEbFutdB98k5UFZdQMYPaBkZSxknZ7yPMpvS29fRhKXUmPBwzOJfYihhyIgqIMIswy9TCPuP4pFfU1lCl17+t6QOobfEUUFKcw1E730mI+WlFtKqtY6GU4RFncCgyirQ0DigIM77+mHMZi3WKAVBJYTJZ0cHvthrrBSSh0jhWrB08jYCzilXE5SwnC3NUcuiKjjGY2uHLXXPUDztNJPYwFDmvhfscaUQVNGUJXmA4FALHF8cxAlJois2X6agdwXK+afpYo4E5MghErGy6WBB/KoAxSIRdX70VnM/YyuG9divcXLPkmHZU/WvADtg923rWgc7LEtFlKnuZssF2LS+FR+9hhSOx1FEUo5OP7UDV4FZL9aJgCf4yCq8tx1xryQLSwQo1ZOoIyoiQs2wJV2Cw9faGk6ZoZH46v2nxj+QyEHorqbMez0pSHwN/wlvygnDKLMB3+2ID5BIgE="

services:
- mongodb

install:
  - pwd
  - cd server
  - ls
  - npm install -g node
  - npm install -g lokijs
  - npm install -g nodemon
  - npm install -g jsdoc
  - npm install -g newrelic

deploy:
- provider: codedeploy
  access_key_id: AKIAIL3L2MPGHOQZSHUQ
  secret_access_key: &1
    secure: YQ/GzaeG+NGH+nu1SgPNZ4Z9qRVaEnxaZFyZ2/1PdAHyBeDOAOTPuqMNQjQHCd7HmHI6YYZeGYiZWDSqg7yEkDJzr1fAqSa/dAm5TSpxBgTb+koLcF1veRGQQCXhFgMrCsbeMz59oheXNYq85/mPxbq1eSJs368NUCbgMA4BU4O/N3bdm6HWhG6G/lkJLpseqsB/vyPRZNhg9jpR7qU0gL5NRvPuG4p18BreIQVR41LS0TyJ3h8oGITA/LM0LWu6JwazODpIJtH6TKbq6jyBNgWUTB9DOHQaCJgkg1io4BfwypXvnyVBeg6tq1LbriO5/BE5FDt9up6oAeUKF0Lgl1cKFHxgV9ncRTfpuAW9pHXSLlXJNoNWK6jCI+FbRWNnKRXvo/Js0yNuylDXtG+eqSOQ1D5QflYsUceh4BuiXN1erSTf8I3J3rRKAKBDLD2A679Mf0QaVGCGPXdH+LLEFnutz5piyQrlLeuysBQMscDr/zB5gHhe1TqcTlcR/XSXRB3THx6Y8INC3Gz/s85AiiDBe8Yl6VHmZmv7gbHt7oDvk7gKX4969+Z6vFtSpUldlElHA1Yf29V6CwR9fnyjh9wbtg1NQM973V8EtY5lfIHhoydv929ejTEq11MnsWS9vmZuH/U35dHtah3vZjJAb3O5pNWZf51RafhKuzC4YK4=
  application: advse-project01
  deployment_group: travisgroup
  region: eu-west-2
  on: &2
    repo: SoftwareEngineeringG02/Project01
    branch: chris-server

notifications:
  slack:
    secure: "nc8meBnt7dOoHlKq5if5DfFLOB3gphUzPM2L022f6BbnEvz8mRDnNDSQ2OAOMI4w0+03dqHiMqik999URhhlyPi5EFDIWZ6NZfAk9LTJlHET0u+/b3H6RMK0CHFw3VmLi9R0CLQUxlxa6H3/Keghp2yaAQ/d8319MQX8LUtBtZ517ZIAQ9RObbECoTk8wCQHTIuk2gXIdrw76MDjdYQi3IhgcXalEuZk92ZUwMvE8OmLc3B0KICESj8hk2pHwH2PAJ1EXuk/hey5FhhFvwENfOkUGqDrrQExRsuwv+3bqyD2BZorHWcSfRQ4BQw4ByvkggEGRtT4kCpnK7qmuhXYLuFlCIEJB9FTnbcfc8C4W4+cZ/mtIKbt+Wb8KPvZxvfrBTzuSX3Fe1j9Xuevwy8UjMVd//bvqNHXo7MJczd0vkxPp10qkWrrhZQmJVYewBB5yAbCDBLpEQ1MJlzxVZ9Dr0LWEv3qIDMoL3U+fZot72cRK4hdg6oMVBLbsk0g/sKYBGLX8BdlQcz6jN4azmBFASN7ciqZx0I18u2Fbf6oxkZZNPH5xhKvVC+yrxX0y95Dd2V2rdTQ6wmwFujzOEJazCSVaf16w0YiN1/vLmUFzWwUbMXVyTQD5fX2aEEgxiLT8Ph04NseDAM4AALyQM9ky6wOCcTPNwI7ChE+jJdmEa8="

after_deploy:
  - npm install
